### PR TITLE
Custom subtitles

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Custom subtitles and notifications with settings to tweak color, position and timeout.

### CODE REVIEW

**Comment by nriley** [comment]
In the backlog session we agreed to change `user.subtitles_all_screens` to an enum including values such as {all screens, screen of focused window/app, screen of current cursor, main screen}.

**Review by nriley — CHANGES_REQUESTED** [review]
(see above)

**Comment by AndreasArvidsson** [comment]
@nriley Updated. I only have one screen on this computer. I'm pretty sure about the code, but if you have multiple screens please give the different options a try.

**Review by nriley — APPROVED** [review]

**Comment by nriley** [comment]
@AndreasArvidsson all the options seem to make sense. I made a couple documentation changes — if you're OK with them, I think we're ready to merge.

**Pull request merged**
