### PR TITLE
Anchor the VSCode please command

### PR DESCRIPTION
**Pull request by jaresty**
- I was frequently getting this triggered in the middle of other commands
- I don't think it makes sense to chain this command

### CODE REVIEW

**Review by nriley — CHANGES_REQUESTED** [review]
From the community backlog session — this now creates a difference between the VSCode and the other please implementations in community. I would recommend you consider addressing #1536 or modifying the other implementations at the same time as this one.

**Comment by jaresty** [comment]
I'm opting to simply anchor the current please commands
- since jetbrains is already different, I'm not sure which way to go if I were to try and consolidate with the single overrideable helper.
- if it is preferable to come up with a single overrideable helper, I'm happy to do so but would like some guidance what to do with jetbrains

**Comment by auscompgeek** [comment]
I don't see how the JetBrains equivalent behaves any differently to the VSCode one. They both open a command palette and optionally insert some text.

**Comment by jaresty** [comment]
It behaves the same, but the naming is different. I heard that the ask was to make a single talon definition that had overridden implementations in each application. If I do that for jetbrains, users who rely on the "action" usage will not have that anymore. Is that what I should do?

**Comment by jaresty** [comment]
Ok, I think I'll put together a version of this that consolidates on a single overrideable command so we can discuss/decide which works better.

**Comment by jaresty** [comment]
Here is a version of this that does that: https://github.com/talonhub/community/pull/1537

**Comment by nriley** [comment]
Replaced by #1537

**Pull request closed without merging**
