### PR TITLE
Added support for decimal numbers

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
`"numb fifty five point two"` -> `55.2`

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
@nriley I ready for review :)

**Review by nriley — APPROVED** [review]

**Comment by auscompgeek** [comment]
Does this address #1245?

**Comment by nriley** [comment]
> Does this address #1245?

Mostly, I think. I wonder if we want to replace our dictation mode implementation with this too?

**Comment by AndreasArvidsson** [comment]
> > Does this address #1245?
> 
> Mostly, I think. I wonder if we want to replace our dictation mode implementation with this too?

In my own repository I am using the same prose capture for dictation. That means I automatically get parity between the prose formatters and dictation mode.
I definitely think we should use the same captures whenever possiblepLooks like in community we do have some work to clean this up.

**Pull request merged**
