### PR TITLE
Added navigation steps command

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Implemented new more powerful navigation grammar
* go left
* go left left down
* go 5 left 2 down
*  go word left
* go 2 words right
* go 5 left down down 4 words left

This is fully backwards compatible with the existing `go left`, `go word right` and `go left left down down` grammars. Only here combining them in a single (more powerful) command

### CODE REVIEW

**Comment by pokey** [comment]
I feel you are starting down the path to rebuilding https://github.com/talonhub/community/tree/main/plugin/text_navigation

**Comment by AndreasArvidsson** [comment]
> I feel you are starting down the path to rebuilding https://github.com/talonhub/community/tree/main/plugin/text_navigation

The purpose of this is that it's fully backwards compatible width existing commands. We don't want users to have to learn multiple different ways of navigating when one grammar can do it all. I don't think that many people use to navigate command because it's to complicated.

**Comment by pokey** [comment]
Not saying is is necessarily a bad thing, just want to make sure we think through the relationship here and whether we want to borrow anything from there

**Review by nriley — APPROVED** [review]

**Comment by nriley** [comment]
I'm OK with this. I have some alternative commands for "go word left" and "go word right" (I use compass directions for these) — not sure it is worth accommodating these as, e.g. "go 2 east down"?

Also this does allow "go 2 words down" even though this is nonsensical; again, not sure if this is worth fixing.

**Comment by AndreasArvidsson** [comment]
> I'm OK with this. I have some alternative commands for "go word left" and "go word right" (I use compass directions for these) — not sure it is worth accommodating these as, e.g. "go 2 east down"? Seems like this would require some significant rearchitecting when I'm happy doing what I do now, e.g. "go east second".
> 
> Also this does allow "go 2 words down" even though this is nonsensical; again, not sure if this is worth fixing.

You just need to update the spoken form of your arrow keys and that's it.

**Comment by nriley** [comment]
Yeah, I approved it anyway, just noting a few potential caveats!

**Pull request merged**
