### PR TITLE
configurable number prefix

### PR DESCRIPTION
**Pull request by jaresty**
- Attempt to implement optional numb prefix
- The tags need to be logically combined

### CODE REVIEW

**Comment by jaresty** [comment]
This is an alternative approach to requiring all users to [adopt a new prefix](https://github.com/talonhub/community/pull/1337)

**Comment by auscompgeek** [comment]
I think instead of adding complexity to the matcher, we should instead have one tag to disable unprefixed numbers. See #943 for my thoughts

**Comment by jaresty** [comment]
Thanks for the suggestion! I didn't totally understand it, though. Can you show me some pseudocode demonstrating what you mean? (Or another PR that I could look at is ok as well)

**Comment by jaresty** [comment]
Ah, I think I'm getting it. You mean to suggest removing the mouse  grid check altogether?

**Comment by fidgetingbits** [comment]
The approach auscompgeek mentioned seems cleaner to me.

iiuc the idea would be to have a single tag  user.disable_unprefixed_numbers and then you don't need the additional mouse grid testing you have in your new files. 

The mouse grid test can then also be removed from numbers.talon. And then the mouse grid code will need to be modified to set the new user.disable_unprefixed_numbers tag when active in order to turn off unprefixed numbers, so it can then use unprefixed numbers for its own purposes.

**Comment by jaresty** [comment]
Something like this? https://github.com/talonhub/community/pull/1342

**Comment by knausj85** [comment]
I think we have sufficient consensus, closing this issue in favor of  #1342

**Pull request closed without merging**
