### PR TITLE
Add helpers for appending to the clipboard

### PR DESCRIPTION
**Pull request by jaresty**
- Sometimes you want to append to the clipboard instead of replacing it

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
Notes from the community meetup. 
We think this is a bit confusing and should probably be part of a proper clipboard manager instead of just appending your existing clipboard entry. 
This needs a bit more polish before we could push it to community, but its close:
https://github.com/AndreasArvidsson/clippy

**Comment by jaresty** [comment]
FWIW - the use case for this is distinct from clipboard history.  Especially when working with LLMs, it is useful to collect context in a single location - I would not want it to be separate clipboard entries, for that reason.

**Comment by AndreasArvidsson** [comment]
Couldn't you just store it in a variable in Talon instead. If you just need a storage and not actual clipboard use?

**Comment by jaresty** [comment]
I use the clipboard as a way to collect context.  In the talon-ai-tools repository, you can run prompts on the clipboard contents directly.  It is possible to solve in other ways, but personally I will probably implement this as a helper for myself if the community maintainers opt not to take it.

**Comment by jaresty** [comment]
FWIW - I do love the idea of having a builtin clipboard manager, though! 🙇

**Comment by jaresty** [comment]
I'm closing this as it seems like it's not going anywhere-we've also found a different approach that works fine for talon-ai-tools.

**Pull request closed without merging**
