### PR TITLE
Move all talon files into a different directory

### PR DESCRIPTION
**Pull request by jaresty**
The idea behind this is that, since the python files should change less often than the talon files, we might be able to move all of the talon files into their own repository such that most users could share the same python base files and only fork the talon file repository if they wanted to customize their commands.

I think this aligns with Sandy Metz's philosophy to "[depend on things that change less often than you do](https://arc.net/l/quote/rpkmjabx)"

### CODE REVIEW

**Comment by pokey** [comment]
I'm a bit hesitant about this direction. I am an advocate of related things being close together. When we have a proper package manager in talon, my understanding is that packages will be able to have their own talon files, so I'm not sure I see how this PR gets us better prepared for when we have a package manager

Fwiw, we actually went in the exact opposite direction two years ago, and I think the reasons for that move still hold today (https://github.com/talonhub/community/pull/897)

**Comment by jaresty** [comment]
I think we've learned that people have reasons for customizing their spoken vocabulary away from the stock commands. This would be the same even if these were split into separate packages. While I also like as a general rule to keep related things together, I could envision a this implementation-vocabulary split still working in a package manager driven system. Imagine this: there is a base package that defines the implementation (Python), and there are a few alternative packages that can be chosen from for the spoken forms (long form, terse, etc). This would allow people who are interested to share their custom vocabularies without having to make the Python code tied to also defining the spoken forms.

**Comment by nriley** [comment]
> I'm a bit hesitant about this direction. I am an advocate of related things being close together. When we have a proper package manager in talon, my understanding is that packages will be able to have their own talon files, so I'm not sure I see how this PR gets us better prepared for when we have a package manager
> 
> Fwiw, we actually went in the exact opposite direction two years ago, and I think the reasons for that move still hold today (#897)

I agree with this and would prefer the strategy proposed in #1418.

**Comment by jaresty** [comment]
That works for me.

**Pull request closed without merging**
