### PR TITLE
feat: Add dark_mode option in settings

### PR DESCRIPTION
**Pull request by Spiteless**
Just learned that dark_mode exists, would like to have an easier settings option for users.

### CODE REVIEW

**Review by fidgetingbits — APPROVED** [review]

**Comment by fidgetingbits** [comment]
My only minor concern about this is that if people already have `imgui.dark_mode = true` elsewhere in a different settings file, this will potentially clash suddenly and I guess possibly switch them out of dark mode depending on precedence. For now it's kind of an unavoidable problem, so just have to accept it I think. That said, I will wait to see if anyone else says anything.

**Comment by Spiteless** [comment]
We could leave it commented out so that it doesn't override any configs

**Comment by fidgetingbits** [comment]
Oh right, ya that works. Looks like that's the case for a bunch of the settings anyway.

**Comment by Spiteless** [comment]
Changed to `uncomment if` format

**Pull request merged**
